In [1]:
import numpy as np

# generate data

In [2]:
# In real world, you cannot learn how the data was generated. So do not rely on this function when coding your lab.
def generate_data(dim, num):
    x = np.random.normal(0, 10, [num, dim])
    coef = np.random.uniform(-1, 1, [dim, 1])
    pred = np.dot(x, coef)
    pred_n = (pred - np.mean(pred)) / np.sqrt(np.var(pred))
    label = np.sign(pred_n)
    mislabel_value = np.random.uniform(0, 1, num)
    mislabel = 0
    for i in range(num):
        if np.abs(pred_n[i]) < 1 and mislabel_value[i] > 0.9 + 0.1 * np.abs(pred_n[i]):
            label[i] *= -1
            mislabel += 1
    return x, label, mislabel/num

In [3]:
# example
x, y, mr = generate_data(5, 100)

In [4]:
x[:5], y[:5],x[1]

(array([[  2.96830413,  -0.33636325,   1.40085378,  11.1629043 ,
           3.19317492],
        [-10.36894829,   3.61613569, -16.41449551,   5.02120705,
          -5.68167233],
        [ -1.34977348,  13.46827881,   0.35879215,  -4.58768624,
           0.74571883],
        [ -2.82758556,  -6.51875305,   0.73985264,  13.38719043,
         -17.8776355 ],
        [ -6.8935832 ,   7.00144929, -10.55640338,   4.03014373,
           2.08046176]]),
 array([[ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [ 1.]]),
 array([-10.36894829,   3.61613569, -16.41449551,   5.02120705,
         -5.68167233]))

# construct and train your models

In [5]:
from svm1 import SVM1

In [6]:
from svm2 import SVM2

In [7]:
def normalize(x):
    return(x-np.min(x))/(np.max(x)-np.min(x))

In [8]:
def get_datasets():
    X,y,mr =generate_data(5,100)
    X_norm = normalize(X)
    X_train = X_norm[:int(len(X_norm)*0.8)]
    X_test = X_norm[int(len(X_norm)*0.8):]
    y_train = y[:int(len(X_norm)*0.8)]
    y_test = y[int(len(X_norm)*0.8):]
    return X_train,y_train,X_test,y_test

In [9]:
X_train,y_train,X_test,y_test = get_datasets()

In [10]:
model1 = SVM1(max_iter=1000) 
model1.fit(X_train,y_train)

'train done!'

In [11]:
model2 = SVM2(max_iter=1000) 
model2.fit(X_train,y_train)

'train done!'

# predict and compare your results

In [12]:
print("mislabel rate:{}".format(mr))
print("acccucy:{:.4f}".format(model1.score(X_test, y_test)))

mislabel rate:0.04
acccucy:0.4000


In [13]:
print("mislabel rate:{}".format(mr))
print("acccucy:{:.4f}".format(model2.score(X_test, y_test)))

mislabel rate:0.04
acccucy:0.6000
